codecov:
  require_ci_to_pass: yes
  
coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto

ignore:
  - "dist/**/*"
  - "coverage/**/*"
  - "node_modules/**/*"
  - "*.config.js"
  - "*.config.ts"
  - "tests/**/*"

comment:
  layout: "header, diff"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes